### ISSUE TITLE
Sublime Text 2 - Comment breaking highlighting

### ISSUE THREAD

**Issue by pappalar** [ariatemplates/sublime-ariatemplates-highlighter#2]
As requested, copying here the issue:

https://github.com/ariatemplates/editors-tools/issues/4

Thank you for the fast response! :)

**Comment by juliandescottes** [comment]
@racer1988 I released a new version of the highlighter which gives better results for CSSTemplates. 

The CSSTemplate highlighter no longer relies on the built in js/css parser. Instead it uses simplified rules for highlighting CSS syntax while remaining compatible with AT syntax. So it's a compromise between supporting the AriaTemplates syntax and the CSS syntax.

Tricky CSS expressions will not be recognized as well as they were. On the other side, the highlighting is no longer failing if you insert a {statement ...} in the middle of a ruleset.

You can install it through Package Control. Let me know if you find issues with CSSTemplates.

**Comment by pappalar** [comment]
Thanks! Will let you know (when it goes live) if I found something :)
